In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [3]:
df=pd.read_csv('covid_toy.csv')

In [4]:
df.head(5)

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.drop('has_covid',axis=1),df['has_covid'],test_size=0.20,random_state=42)

In [7]:
x_train.head()

    age  gender  fever cough     city
55   81  Female  101.0  Mild   Mumbai
88    5  Female  100.0  Mild  Kolkata
26   19  Female  100.0  Mild  Kolkata
42   27    Male  100.0  Mild    Delhi
69   73  Female  103.0  Mild    Delhi

In [8]:
from sklearn.compose import ColumnTransformer

In [15]:
transform=ColumnTransformer(transformers=[
    ('tran1',SimpleImputer(),['fever']),
    ('tran2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough'],)
    ('tran3',OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])
],remainder='passthrough')

TypeError: 'tuple' object is not callable